Fixed SyncFragment Crash on Application Install
odk-x/services pull request #201
Opened 2021-04-02 19:01 UTC by VarunT11

**Issue Reference**: https://github.com/odk-x/tool-suite-X/issues/234
**Changes Performed**: Added the code to check if `syncAttachmentState` is not `null` in `getSyncAttachmentStateIndex` Method of `SyncFragment`

2021-04-02 19:03 UTC, wbrunette commented
runtests

2021-04-02 19:05 UTC, wbrunette commented
@pawanharariya can you help us review this change since this is related to your changes?

2021-04-03 10:50 UTC, pawanharariya commented
@VarunT11 The above check done prevents the crash but the variable `syncAttachmentState` still remains `null`. To fix this in the `onCreate()` method of `syncFragment` the variable can be initialized when the `if` case fails.

https://github.com/odk-x/services/blob/1a0b8db2b52a6caf9581dc8ab68a7e6e22ff413d/services_app/src/main/java/org/opendatakit/services/sync/actions/fragments/SyncFragment.java#L146

an else condition can be added here which initailizes `syncAttachmentState` to` SyncAttachmentState.SYNC`

2021-04-03 13:27 UTC, VarunT11 commented
@pawanharariya I actually checked for the Value of `syncAttachmentState` when the Sync Activity started for the First Time and the Second Time after installing the Application. The value remained `null` for the first time as described in the issue but was assigned a value according to the Sync Preference selected during the First Run of the Activity. Thus `syncAttachmentState` did not remain `null` anymore.

2021-04-03 18:15 UTC, pawanharariya commented
@VarunT11 Yeah you are right that works. But I feel  `syncAttachmentState` can be initialized in the `onCreate()` method in addition to the `null` check that you have made, because for some time the app is in the state where  `syncAttachmentState` is `null`
Maybe @wbrunette can guide us more on this.

2021-04-03 18:27 UTC, VarunT11 commented
@pawanharariya Okay, I got your point. I will make the required changes!

2021-04-03 23:53 UTC, wbrunette requested changes
I think the syncAttachmentState!=null check should be in the onCreate before even calling the function.

2021-04-04 05:03 UTC, linl33 commented
runtests

2021-04-04 06:26 UTC, wbrunette approved these changes

2021-04-04 06:27 UTC, merged