Unit Test suites for ViewModels
odk-x/services pull request #243
Opened 2022-06-27 10:14 UTC by sanyud24

Tested various MutableLiveData ViewModel classes for the following packages:
- ### package org.opendatakit.services.sync.actions.viewModels;
   - AbsSyncViewModel
   - LoginViewModel
   - SyncViewModel
   - VerifyViewModel
- ### package org.opendatakit.services.preferences;
   - PreferenceViewModel
   - Added **android.arch.core.executor.testing.InstantTaskExecutorRule**:  swaps the background executor used by the Architecture Components with a different one which executes each task synchronously.

2022-06-27 10:44 UTC, sanyud24 commented
Hi, @wbrunette  @Lamouresparus I've finished testing the ViewModel classes.

2022-07-06 02:30 UTC, wbrunette commented
@sanyud24 can you fix the merge conflict

2022-07-06 15:30 UTC, wbrunette requested changes

2022-07-06 15:30 UTC, wbrunette commented on services_app/src/test/java/org/opendatakit/services/sync/actions/viewModels/viewModels/AbsSyncViewModelTest.java
> +        String serverUrl = "https://odk-x.org/";
please use constants

2022-07-06 15:30 UTC, wbrunette commented on services_app/src/test/java/org/opendatakit/services/sync/actions/viewModels/viewModels/AbsSyncViewModelTest.java
> +        long time = LocalTime.parse("12:30").getHour();
use timestamp utilities from android library

2022-07-06 15:30 UTC, wbrunette commented on services_app/src/test/java/org/opendatakit/services/sync/actions/viewModels/viewModels/VerifyViewModelTest.java
> +        String verifyType = "verified";
please use constants

2022-07-06 15:30 UTC, wbrunette commented on services_app/src/test/java/org/opendatakit/services/sync/actions/viewModels/viewModels/LoginViewModelTest.java
> +        loginViewModel.updateFunctionType("function");
please use constants

2022-07-06 22:09 UTC, sanyud24 commented
Hi @wbrunette,  Should I also create constants for the boolean fields?

2022-07-06 23:09 UTC, wbrunette commented
@sanyud24 that is a great question and the answer is it depends. If you are assigning meaning in setting up your tests then yes, but you should name the constant the meaning. If it's simply just true/false then no. We can discuss more at our next meeting because there is more to explain and it's a good to discuss.

2022-07-07 18:11 UTC, wbrunette approved these changes

2022-07-07 18:11 UTC, merged