Unit Test suites for AsyncTasks
odk-x/services pull request #244
Opened 2022-07-07 15:22 UTC by sanyud24

Tested custom AsyncTask classes.
## package org.opendatakit.services.resolve.task

### CheckpointResolutionListTask 
- Used Roboelectric `ShadowEnvironment.setExternalStorageState(Environment.MEDIA_MOUNTED)` to change the 
   "card-status = mounted" and to set mock external storage.
- Mockito to mock ResolutionListener class
### ConflictResolutionListTask

2022-07-07 18:47 UTC, wbrunette requested changes
Your setup creates a background task each time. Does the task run? What happens if you cancel the task? What about making sure the task finishes?

2022-07-07 18:47 UTC, wbrunette commented on services_app/src/test/java/org/opendatakit/services/resolve/CheckpointResolutionListTaskTest.java
> +    public void checkIfResolutionListener_isAvailable() {
This test does not seem to verify any behavior. Normally you see an assert to verify it's working

2022-07-07 19:57 UTC, sanyud24 commented
> Your setup creates a background task each time. Does the task run? What happens if you cancel the task? What about making sure the task finishes?

Yeah, ur right!! added the asynctask.execute to make sure task runs and asynctask.cancel to make sure asynctask thread stops.

2022-07-07 20:05 UTC, sanyud24 commented
Hi @wbrunette, There's still the error of OdkConnectionFactorySingleton not initialized as it's a final class and mockito can't mock it. I'll look into the issue.

2022-07-20 03:22 UTC, wbrunette commented
@sanyud24 did you solve the issue on of the mockito?

2022-07-20 06:01 UTC, sanyud24 commented
> @sanyud24 did you solve the issue on of the mockito?

Yeah @wbrunette , I'm almost done with it.

2022-08-11 18:35 UTC, sanyud24 commented
Hi, @wbrunette fixed this PR and added a base test class.

2022-08-12 16:27 UTC, wbrunette approved these changes

2022-08-12 16:28 UTC, merged