Fix Broken UI Test for all Admin Configurable Settings
odk-x/services pull request #282
Opened 2024-03-24 20:10 UTC by Stryker101

**This is a pull request raised for issue https://github.com/odk-x/tool-suite-X/issues/470

**Reason for Fix:
There are configurable settings available for a normal user of the app and there are configurable settings available for a user with admin privileges. The UI tests for these settings screen was broken following a rework of the settings screen. This PR was raised to fix the broken UI Test for the configurable settings that are available to a user with ADMIN privileges. These tests includes the following:

 -AdminConfigurableServerSettingsFragmentTest.java
 -AdminConfigurableDeviceSettingsFragmentTest.java
 -AdminConfigurableTablesSettingsFragmentTest.java

**What was changed in these files:

AdminConfigurableServerSettingsFragmentTest.java
--Nothing changed. this test was fixed when the enableAdminMode(); function in BaseUItest was fixed

AdminConfigurableDeviceSettingsFragmentTest.java
--corrected the reference for the string to be matched.

AdminConfigurableTablesSettingsFragmentTest.java
--corrected the reference for the string to be matched.

2024-03-29 19:32 UTC, Redeem-Grimm-Satoshi commented
Well done! I see some changes made but I haven't tested it yet. Send a screenshot showing how it works at your end ( test passed ) then I can proceed to review from there

2024-03-29 20:41 UTC, Stryker101 commented
Hi @Redeem-Grimm-Satoshi I've  added the screenshot(s) as requested.

2024-04-18 17:45 UTC, Redeem-Grimm-Satoshi requested changes
More work needed

2024-04-18 17:45 UTC, Redeem-Grimm-Satoshi commented on services_app/src/androidTest/java/org/opendatakit/BaseUITest.java
> -                .check(matches(isDisplayed()));
Why remove the password dialog verification check?

2024-04-18 17:45 UTC, Redeem-Grimm-Satoshi commented on services_app/src/androidTest/java/org/opendatakit/services/preferences/fragments/AdminConfigurableTablesSettingsFragmentTest.java
> +                .perform(RecyclerViewActions.actionOnItem(hasDescendant(withText(R.string.odkx_tables)),
why change the string `tool_tables_settings` ( Table-specific Settings ) to `odkx_tables`( ODK-X Tables ) ? 

Any reason for that?

2024-04-18 17:53 UTC, Stryker101 commented on services_app/src/androidTest/java/org/opendatakit/services/preferences/fragments/AdminConfigurableTablesSettingsFragmentTest.java
> +                .perform(RecyclerViewActions.actionOnItem(hasDescendant(withText(R.string.odkx_tables)),
That's the current string resource for the displayed text.

2024-04-18 17:56 UTC, Stryker101 commented on services_app/src/androidTest/java/org/opendatakit/BaseUITest.java
> -                .check(matches(isDisplayed()));
Bacause that view isn't there anymore. Check for what isn't there is what broke that test. We can get on a skype call and run these test together.

2024-04-18 17:56 UTC, Stryker101 commented
> More work needed

Those questions have been answered.

2024-04-18 19:20 UTC, Redeem-Grimm-Satoshi commented
> > More work needed
> 
> Those questions have been answered.

I don't think you've understood me well. Answer the questions I asked up, It's that simple!

2024-04-18 19:30 UTC, Stryker101 commented
> > > More work needed
> > 
> > Those questions have been answered.
> 
> I don't think you've understood me well. Answer the questions I asked up, It's that simple!

If you think i misunderstood you , i think the productive thing to do is explain what you think i missed. I gave a response based on how i understood your previous comment.

2024-05-15 12:17 UTC, Redeem-Grimm-Satoshi approved these changes

2024-05-21 20:35 UTC, wbrunette approved these changes

2024-05-21 20:35 UTC, merged