Setup CircleCI to store build artifacts
odk-x/services pull request #285
Opened 2024-05-22 15:28 UTC by nuilewis

This adds a config to deploy build artifacts to GitHub Releases which can be used for the Tables tests.

2024-05-22 15:38 UTC, Redeem-Grimm-Satoshi commented
@nuilewis Awesome, currently having one failed test?

2024-05-22 15:41 UTC, wbrunette commented
We changed the way we are publishing. See Androidlibrary and AndroidCommon
https://github.com/odk-x/androidlibrary/blob/upgrade-jdk11/.circleci/config.yml

2024-05-22 15:53 UTC, nuilewis commented
> We changed the way we are publishing. See Androidlibrary and AndroidCommon https://github.com/odk-x/androidlibrary/blob/upgrade-jdk11/.circleci/config.yml

Uh, okay. I figured this is just for the android library and android common since they are published as packages.

I added a confIg to push the builds apks from the CircleCI build jobs to GitHub, so we can use them for the Tables tests. I remember we spoke one time, and we discussed how the current setup for tables was too complicated because it had to make multiple requests to the circleci api to get the build artifacts from previous jobs then download the apks before installing for the tests, then you suggested we publish the build artifacts to Github rather.

2024-05-22 15:55 UTC, nuilewis commented
> @nuilewis Awesome, currently having one failed test?

The tests are failing because they are configured to run on the xlarge resource class on circleci which my personal account doesn't have access to.

2024-05-22 16:24 UTC, wbrunette commented
> > We changed the way we are publishing. See Androidlibrary and AndroidCommon https://github.com/odk-x/androidlibrary/blob/upgrade-jdk11/.circleci/config.yml
> 
> Uh, okay. I figured this is just for the android library and android common since they are published as packages.
> 
> I added a confIg to push the builds apks from the CircleCI build jobs to GitHub, so we can use them for the Tables tests. I remember we spoke one time, and we discussed how the current setup for tables was too complicated because it had to make multiple requests to the circleci api to get the build artifacts from previous jobs then download the apks before installing for the tests, then you suggested we publish the build artifacts to Github rather.

Your approach is valid; however, a "snapshot" build should not be an official release. It should be like the libraries where we test things BEFORE they become an "official release". We are using the packages to store the "snapshots".

2024-05-22 16:41 UTC, nuilewis commented
> > > We changed the way we are publishing. See Androidlibrary and AndroidCommon https://github.com/odk-x/androidlibrary/blob/upgrade-jdk11/.circleci/config.yml
> > 
> > 
> > Uh, okay. I figured this is just for the android library and android common since they are published as packages.
> > I added a confIg to push the builds apks from the CircleCI build jobs to GitHub, so we can use them for the Tables tests. I remember we spoke one time, and we discussed how the current setup for tables was too complicated because it had to make multiple requests to the circleci api to get the build artifacts from previous jobs then download the apks before installing for the tests, then you suggested we publish the build artifacts to Github rather.
> 
> Your approach is valid; however, a "snapshot" build should not be an official release. It should be like the libraries where we test things BEFORE they become an "official release". We are using the packages to store the "snapshots".

Okay, I understand.
Now I am a bit confused, if we are using packages for the build apks of the apps, does that mean we would have to consume them in the build.gradle like an actual package? like the way we are currently doing with androidlibray and androidcommon? That's not really what we want right?

Or is it possible to download the "package" files as just files we can then use anywhere?

2024-05-22 17:05 UTC, wbrunette commented
you are correct, it's not supported yet. 

What are your thoughts on using GitHub actions and artifacts? https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

2024-05-22 17:09 UTC, wbrunette commented
Maybe just use the artifact system in CircleCI instead? https://circleci.com/docs/artifacts/#downloading-all-artifacts-for-a-build-on-circleci

2024-05-22 20:17 UTC, nuilewis commented
> you are correct, it's not supported yet.
> 
> What are your thoughts on using GitHub actions and artifacts? https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

Uhm, I think adding a layer of GitHub actions might further complicate the build system, because CircleCI already has its own artifact system, we might as well just use that in my opinion

2024-05-22 20:19 UTC, nuilewis commented
> Maybe just use the artifact system in CircleCI instead? https://circleci.com/docs/artifacts/#downloading-all-artifacts-for-a-build-on-circleci

Alright then, yeah this was similar to the initial approach I did, storing the build files as artifacts then downloading them when running the tables tests.

2024-05-23 15:48 UTC, nuilewis commented
Hello @wbrunette
I have updated the config to store the build artifacts in CircleCI

2024-05-23 19:09 UTC, wbrunette requested changes

2024-05-23 19:09 UTC, wbrunette commented on .circleci/config.yml
> +#  deploy:
Please remove commented out code.

2024-05-23 19:38 UTC, nuilewis commented on .circleci/config.yml
> +#  deploy:
Alright, done

2024-05-23 19:42 UTC, wbrunette approved these changes

2024-05-23 19:43 UTC, merged